spring:
  application:
    name: SpringSecurity

  datasource:
    url: jdbc:mysql://localhost:3306/webchatt?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&zeroDateTimeBehavior=convertToNull
    username: root
    password: bopanu04
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: false
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080

security:
  jwt:
    secret-key: PPrW7xSTfBwOpRn4/AV6gPzQSnQg+Oi80KdWfCcuAHs=
    expiration-time: 60000
    refreshExpirationMs: 604800000
