spring:
  application:
    name: SpringSecurity

# Shared defaults (apply to all profiles unless overridden below)
  jpa:
    properties:
      org.hibernate.envers.store_data_at_delete: true
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: false
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: ${PORT:8080}

security:
  jwt:
    secret-key: ${JWT_SECRET:PPrW7xSTfBwOpRn4/AV6gPzQSnQg+Oi80KdWfCcuAHs=}
    expiration-time: ${JWT_EXPIRATION:60000}
    refreshExpirationMs: ${JWT_REFRESH_EXPIRATION:604800000}
